version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/app/public:/app/public
      - ./frontend/app/src:/app/src
    ports:
      - "3000:3000"

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api-server
    env_file:
      - ./api-server/.env
    volumes:
      - ./api-server/src:/app/src
    ports:
      - "5000:5000"

  sbv2-server:
    # 例としての音声合成サーバ
    build:
      context: ./SBV2
      dockerfile: Dockerfile
    container_name: sbv2
    volumes:
      - ./SBV2/model_assets:/home/user/Style-Bert-VITS2/model_assets
    ports:
      - "50022:5000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ "gpu" ]
    command: python server_fastapi.py

  # pyserver:
  #   # RAG用のサーバ
  #   build:
  #     context: ./pyserver
  #     dockerfile: Dockerfile
  #   container_name: pyserver
  #   ports:
  #     - "5005:5005"
  #     - "5006:5006"
  #   volumes:
  #     - ~/docker_projects/viida-beta/pyserver/src:/app
  #   depends_on:
  #     - backend
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 2
  #             capabilities: [ "gpu" ]

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    # user: "132:65534"  # ホストマシンにおけるmongodbのUIDとGID
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017 # host:container
    volumes:
      - ./mongoDB:/var/lib/mongo
