

heroine_name_list: [
  アイリ,
  アイラ,
  アカネ,
  アスカ,
  アヤ,
  アヤメ,
  アリサ,
  アンナ,
  イズミ,
  イチカ,
  イノリ,
  ウミ,
  エミリー,
  エリ,
  エリカ,
  オトハ,
  カエデ,
  カオリ,
  カナ,
  カナコ,
  カノン,
  カレン,
  キララ,
  キョウコ,
  キヨコ,
  クルミ,
  クレア,
  ケイコ,
  コトネ,
  コトミ,
  コハル,
  サキ,
  サクラ,
  サトミ,
  サナ,
  サヤ,
  サユリ,
  シオリ,
  シズカ,
  シズク,
  シノ,
  シホ,
  ショウコ,
  ジュンコ,
  スズカ,
  スズナ,
  スズネ,
  スミレ,
  セナ,
  セリナ,
  ソラ,
  タエ,
  チアキ,
  チカ,
  チハヤ,
  チホ,
  ツバキ,
  ツバサ,
  ティア,
  トモエ,
  トモカ,
  ナギサ,
  ナナ,
  ナナコ,
  ナミ,
  ナヨ,
  ナルミ,
  ニーナ,
  ネネ,
  ノゾミ,
  ハルカ,
  ハナコ,
  ハルナ,
  ヒカリ,
  ヒナ,
  ヒナタ,
  ヒミコ,
  フウカ,
  フミノ,
  フユコ,
  マイ,
  マフユ,
  マナ,
  マホ,
  マミ,
  マユ,
  マユミ,
  ミク,
  ミサ,
  ミサキ,
  ミツキ,
  ミナ,
  ミナミ,
  ミヨ,
  ミライ,
  ミリア,
  モモ,
  モモカ,
  ユイ,
  ユキ,
  ユズキ,
]
hero_name_list: [
  アキラ,
  アツシ,
  アユム,
  アラタ,
  イサオ,
  イツキ,
  イノキ,
  ウィリアム,
  エイジ,
  カイト,
  カズキ,
  カズヤ,
  カナタ,
  カイジ,
  キョウスケ,
  キョウヘイ,
  キョウマ,
  クロム,
  ケイト,
  ケンジ,
  ケンタ,
  ケント,
  コウ,
  コウキ,
  コウタ,
  コウタロウ,
  コウヘイ,
  サイタマ,
  サトシ,
  ザナン,
  シキ,
  シン,
  シンイチ,
  シンジ,
  ジロウ,
  スバル,
  セイジ,
  セイヤ,
  ソウタ,
  ソウマ,
  タイガ,
  タカシ,
  タカフミ,
  タクミ,
  タクヤ,
  タツヤ,
  ツトム,
  テツ,
  テツヤ,
  トオル,
  トシキ,
  ナオキ,
  ナオヤ,
  ナツキ,
  ナツオ,
  ナリタ,
  ニト,
  ハジメ,
  ハル,
  ハルト,
  ハルオミ,
  ヒカル,
  ヒデキ,
  ヒロ,
  ヒロキ,
  ヒロシ,
  フミヤ,
  フユト,
  マコト,
  マサキ,
  マサル,
  マナブ,
  マモル,
  マイケル,
  ミキト,
  ミツル,
  ミノル,
  キサラギ,
  メギス,
  ユウ,
  ユウジ,
  ユウト,
  ユウマ,
  ユウキ,
  ユウヤ,
  ユウイチ,
  ユウタ,
  ヨシキ,
  ヨシオ,
  リク,
  リョウ,
  リョウマ,
  リョウヘイ,
  リョウタ,
  リョウジ,
  リンタロウ,
  レイ,
  レン,
  ロクロウ,
  ロン,
  ワタル,
]